### ISSUE TITLE
Plugin is missing from Cura marketplace.

### ISSUE THREAD

**Issue by skyguy94** [macdylan/Snapmaker2Plugin#11]
Someone on the snapmaker facebook forum noticed the plugin was missing from the marketplace. I'm not sure if that's intentional or if it can be fixed. Current advice is to have them copy the .zip from the releases or pull directly from the repo.

**Comment by macdylan** [comment]
The version in the marketplace currently has a serious error So I withdrew it.
I have submitted a new version(releases tag 8.1) for review, But that usually takes 2 weeks or more.

**Comment by skyguy94** [comment]
Takk!
