### ISSUE TITLE
plugin not working on cura 5.0

### ISSUE THREAD

**Issue by ReeCorDs** [macdylan/Snapmaker2Plugin#2]
Hi,

i tried to install your plugin but it doesnt shows me a menu after slicing. any idea?

i also made a fresh install of cura but still not working... :(

![snapmaker2plugin not working](https://user-images.githubusercontent.com/64950722/169345264-f414298d-8ac4-43eb-9157-13f430e4b315.png)

**Comment by macdylan** [comment]
Have you tried these [troubleshooting](https://github.com/macdylan/Snapmaker2Plugin/blob/main/README.en-us.md#troubleshooting-snapmaker-discovery) ?

If it doesn't help, please upload cura.log:
Menu Help -> Show Configuration Folder -> cura.log

**Comment by ReeCorDs** [comment]
> 

my fault! windows firewall blocked cura... works now perfect! thanks alot

**Comment by ReeCorDs** [comment]
Yesterday it worked perfect, now same issue like before....

https://pastebin.com/iTd1EN97

**Comment by macdylan** [comment]
> Yesterday it worked perfect, now same issue like before....
> 
> https://pastebin.com/C4QVmijY

That is a private paste :(
