### ISSUE TITLE
For Firmware 1.14.3

### ISSUE THREAD

**Issue by Meganezaru** [macdylan/Snapmaker2Plugin#8]
Do you have any plans to get this plugin work on firmware 1.14.3?

Thanks!

**Comment by macdylan** [comment]
I have tested on fw 1.14.3.
Please let me know if you have any troubles

**Comment by Meganezaru** [comment]
Thank you for your reply.

![image](https://user-images.githubusercontent.com/3725684/178189323-16d018b9-67d4-46a7-8b2b-78fdfa018a98.png)

I can connect to my A350T via Luban on wifi.
I cannot send Gcode file via Cura on wifi.

I could send with this previous plugin.

I use Windows 10.

Are there any other points to confirm?

**Comment by Meganezaru** [comment]
Just to be sure, I restarted my PC and it worked correctly.
Sorry to bother you.
